# Generated by Django 4.2.3 on 2023-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='Check_Out',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
