# Generated by Django 4.2.3 on 2023-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_attandance_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='Check_Out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attandance',
            name='Check_in',
            field=models.DateTimeField(null=True),
        ),
    ]
